### ISSUE TITLE
菜单背景只能下面设置成圆角吗

### ISSUE THREAD

**Issue by leozhuo** [HanksHu/ZLPopMenuViewController#1]
菜单背景只能下面设置成圆角吗，三角形下面的两个角不方便设置圆角

**Comment by hanks-hu** [comment]
如果你想上下都有圆角的话，可以把tableview切圆角。在https://github.com/HanksHu/ZLPopMenuViewController/blob/master/Code/ZLPopMenuViewController.swift#L33 添加 
```swift
        table.layer.cornerRadius = 5
        table.clipsToBounds = true
```
